@extends('site.layout')
@section('title', $article['seo_title'].' | 34 Build Master')
@section('description', $article['seo_description'])
@section('og_image', $article['image'])
@section('content')
<article class="article-page"><header class="article-header shell"><p class="eyebrow">BUILD MASTER JOURNAL</p><h1>{{ $article['title'] }}</h1><div><span>{{ $article['date'] }}</span><span>อ่าน {{ $article['read_time'] }}</span><span>โดย {{ $article['author'] }}</span></div></header><figure class="article-cover"><img src="{{ $article['image'] }}" alt="{{ $article['cover_alt'] }}"></figure><div class="article-body rich-text">{!! $article['content_html'] !!}</div></article>
<section class="discussion section"><div class="shell discussion-grid"><div><p class="eyebrow">DISCUSSION</p><h2>ร่วมพูดคุยเกี่ยวกับบทความ</h2><p>ความคิดเห็นจะเผยแพร่หลังทีมงานตรวจสอบ เพื่อดูแลพื้นที่สนทนาให้เหมาะสม</p></div><div><div class="comment-list">@forelse($comments as $comment)<article><strong>{{ $comment->author_name }}</strong><time>{{ $comment->created_at?->format('d/m/Y') }}</time><p>{{ $comment->body }}</p>@if($comment->admin_reply)<div class="admin-reply"><strong>ทีม 34 Build Master</strong><p>{{ $comment->admin_reply }}</p></div>@endif</article>@empty<p class="muted">ยังไม่มีความคิดเห็น เป็นคนแรกที่เริ่มบทสนทนาได้เลย</p>@endforelse</div><form class="comment-form" data-comment-form data-endpoint="{{ url('/api/articles/'.$article['slug'].'/comments') }}"><input type="hidden" name="article_title" value="{{ $article['title'] }}"><div class="form-row"><label>ชื่อ<input name="author_name" minlength="2" maxlength="100" required></label><label>อีเมล (ไม่แสดงสาธารณะ)<input name="author_email" type="email" maxlength="255"></label></div><label>ความคิดเห็น<textarea name="body" minlength="3" maxlength="2000" rows="4" required></textarea></label><input class="honeypot" name="website" tabindex="-1" autocomplete="off"><p class="form-feedback" data-form-feedback></p><button class="button" type="submit">ส่งความคิดเห็น →</button></form></div></div></section>
@if($related->isNotEmpty())<section class="section shell"><header class="section-heading"><div><p class="eyebrow">READ NEXT</p><h2>บทความที่เกี่ยวข้อง</h2></div></header><div class="article-grid compact">@foreach($related as $item)<article><a href="{{ route('site.blog.show', $item['slug']) }}"><img src="{{ $item['image'] }}" alt="{{ $item['cover_alt'] }}" loading="lazy"></a><div><span>{{ $item['date'] }}</span><h2><a href="{{ route('site.blog.show', $item['slug']) }}">{{ $item['title'] }}</a></h2></div></article>@endforeach</div></section>@endif
@endsection
