@extends('site.layout')
@section('title', 'เกี่ยวกับเรา | 34 Build Master')
@section('description', 'รู้จักแนวทางการออกแบบและก่อสร้างของ 34 Build Master ที่วางแผนชัดเจนและตรวจสอบคุณภาพทุกขั้นตอน')
@section('content')
@include('site.partials.page-hero', ['title' => 'เกี่ยวกับเรา', 'current' => 'เกี่ยวกับเรา'])
<section class="split-section section shell"><div class="split-copy reveal"><p class="eyebrow">ABOUT 34 BUILD MASTER</p><h2>สร้างคุณภาพ<br><span>ในทุกพื้นที่ของชีวิต</span></h2><p>เราเป็นทีมออกแบบและก่อสร้างที่เชื่อมความต้องการของเจ้าของบ้านเข้ากับแบบ งบประมาณ วัสดุ และการทำงานหน้างานจริง</p><p>ทุกโครงการเริ่มจากการฟังให้ชัด วางแผนให้เห็นภาพ และลงมือด้วยมาตรฐานที่ตรวจสอบได้</p><a class="button" href="{{ route('site.contact') }}">เริ่มคุยกับทีม →</a></div><figure class="split-image reveal"><img src="{{ url('/hero-construction.webp') }}" alt="ทีม 34 Build Master ตรวจแบบหน้างาน"></figure></section>
<section class="stats-band"><div class="shell"><div><strong>10+</strong><span>ปีประสบการณ์</span></div><div><strong>120+</strong><span>พื้นที่ที่ดูแล</span></div><div><strong>4</strong><span>ขั้นตอนควบคุมหลัก</span></div><div><strong>1</strong><span>ทีมดูแลครบวงจร</span></div></div></section>
<section class="process-section section"><div class="shell"><header class="section-heading centered reveal"><div><p class="eyebrow">HOW WE GET IT DONE</p><h2>ขั้นตอนที่ทำให้ทุกฝ่าย<br>เห็นภาพเดียวกัน</h2></div></header><div class="process-grid stagger">@foreach($process as $step)<article><span>{{ $step['number'] }}</span><h3>{{ $step['title'] }}</h3><p>{{ $step['description'] }}</p></article>@endforeach</div></div></section>
<section class="dark-section section"><div class="shell"><header class="section-heading centered reveal"><div><p class="eyebrow">OUR STANDARDS</p><h2>มาตรฐานที่พาโครงการ<br>ไปถึงผลลัพธ์ที่ดี</h2></div></header><div class="value-grid stagger"><article><b>01</b><h3>วางแผนก่อนลงมือ</h3><p>สรุปขอบเขต งบประมาณ และสิ่งที่ต้องตัดสินใจให้ชัดเจน</p></article><article><b>02</b><h3>สื่อสารตรงไปตรงมา</h3><p>อัปเดตสถานะ ปัญหา และทางเลือกให้เจ้าของบ้านเข้าใจ</p></article><article><b>03</b><h3>ตรวจคุณภาพเป็นช่วง</h3><p>ตรวจรับแต่ละขั้นก่อนเดินหน้าสู่งานส่วนถัดไป</p></article><article><b>04</b><h3>ดูแลจนส่งมอบ</h3><p>เก็บรายละเอียดและส่งมอบข้อมูลโครงการอย่างเป็นระบบ</p></article></div></div></section>
<section class="section shell"><header class="section-heading reveal"><div><p class="eyebrow">CLIENT STORIES</p><h2>ประสบการณ์จากลูกค้า</h2></div></header><div class="review-static stagger">@foreach(array_slice($testimonials, 0, 3) as $review)<article><div class="stars">★★★★★</div><blockquote>“{{ $review['text'] }}”</blockquote><strong>{{ $review['name'] }}</strong><span>{{ $review['project'] }}</span></article>@endforeach</div></section>
@include('site.partials.contact')
@endsection
