@extends('site.layout')
@section('title', 'แบบบ้าน | 34 Build Master')
@section('description', 'เลือกชมแบบบ้านตามสไตล์ งบประมาณ และพื้นที่ใช้สอย พร้อมรายละเอียดแต่ละแบบ')
@section('content')
@include('site.partials.page-hero', ['title' => 'แบบบ้าน', 'current' => 'แบบบ้าน', 'image' => url('/approach-homes/contemporary.jpg')])
<section class="section shell"><header class="section-heading reveal"><div><p class="eyebrow">HOUSE COLLECTION</p><h2>ค้นหาแนวทางบ้าน<br>ที่ใกล้กับชีวิตของคุณ</h2></div><p>ใช้ตัวกรองเพื่อดูแบบที่เหมาะสม รายละเอียดทั้งหมดสามารถนำไปต่อยอดให้เข้ากับพื้นที่และงบประมาณจริง</p></header>
<div class="design-filters reveal" data-design-filters><label>สไตล์<select data-filter="style"><option value="">ทุกสไตล์</option>@foreach($styles as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label>งบประมาณ<select data-filter="budget"><option value="">ทุกช่วงงบ</option>@foreach($budgets as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label>ค้นหา<input type="search" data-filter="search" placeholder="ชื่อแบบบ้าน"></label><button class="button button-ghost" type="button" data-filter-reset>ล้างตัวกรอง</button></div>
<div class="design-grid stagger" data-design-grid>@forelse($designs as $design)<article data-design-card data-style="{{ $design['style'] }}" data-budget="{{ $design['budget_category'] }}" data-search="{{ mb_strtolower($design['title'].' '.$design['name']) }}"><a class="design-image" href="{{ route('site.house-designs.show', $design['slug']) }}"><img src="{{ $design['cover_image'] }}" alt="{{ $design['cover_alt'] }}" loading="lazy"><span>{{ $design['style_label'] }}</span></a><div><p>{{ $design['budget_label'] ?: 'สอบถามงบประมาณ' }}</p><h2><a href="{{ route('site.house-designs.show', $design['slug']) }}">{{ $design['title'] }}</a></h2><div class="spec-row"><span>{{ $design['area'] ?: '-' }} ตร.ม.</span><span>{{ $design['bedrooms'] ?: '-' }} ห้องนอน</span><span>{{ $design['bathrooms'] ?: '-' }} ห้องน้ำ</span></div><a class="text-link" href="{{ route('site.house-designs.show', $design['slug']) }}">ดูรายละเอียด →</a></div></article>@empty<div class="empty-state"><h2>ยังไม่มีแบบบ้านที่เผยแพร่</h2><p>ทีมงานกำลังเตรียมข้อมูลแบบบ้านใหม่ กรุณากลับมาตรวจสอบอีกครั้ง</p></div>@endforelse</div><p class="empty-state" data-filter-empty hidden>ไม่พบแบบบ้านที่ตรงกับตัวกรอง</p></section>
@include('site.partials.contact')
@endsection
