@extends('site.layout')
@section('title', $design['seo_title'].' | 34 Build Master')
@section('description', $design['seo_description'])
@section('og_image', $design['cover_image'])
@section('content')
<section class="design-hero"><img src="{{ $design['cover_image'] }}" alt="{{ $design['cover_alt'] }}"><div class="hero-shade"></div><div class="shell"><p class="eyebrow">{{ strtoupper($design['style_label']) }} · HOUSE DESIGN</p><h1>{{ $design['title'] }}</h1><p>{{ $design['description'] }}</p></div></section>
<section class="design-detail section shell"><aside class="design-summary reveal"><p class="eyebrow">PROJECT OVERVIEW</p><h2>{{ $design['name'] }}</h2><p>{{ $design['budget_label'] }}</p><a class="button" href="#contact">ปรึกษาแบบนี้ →</a></aside><div class="design-content reveal"><div class="detail-specs"><div><strong>{{ $design['area'] ?: '-' }}</strong><span>ตร.ม.</span></div><div><strong>{{ $design['bedrooms'] ?: '-' }}</strong><span>ห้องนอน</span></div><div><strong>{{ $design['bathrooms'] ?: '-' }}</strong><span>ห้องน้ำ</span></div><div><strong>{{ $design['floors'] ?: '-' }}</strong><span>ชั้น</span></div><div><strong>{{ $design['parking_spaces'] ?: '-' }}</strong><span>ที่จอดรถ</span></div></div><h2>แนวคิดของแบบบ้าน</h2><div class="rich-text">{!! nl2br(e($design['concept'] ?: $design['description'])) !!}</div>@if($design['features'])<h2>จุดเด่น</h2><ul class="feature-list">@foreach($design['features'] as $feature)<li>{{ $feature }}</li>@endforeach</ul>@endif</div></section>
@if($design['gallery']->isNotEmpty())<section class="gallery-section section"><div class="shell"><header class="section-heading reveal"><div><p class="eyebrow">DESIGN GALLERY</p><h2>ชมรายละเอียดของแบบบ้าน</h2></div><p>คลิกที่ภาพเพื่อเปิดดูแบบเต็มหน้าจอและเลื่อนไปยังภาพถัดไป</p></header><div class="gallery-grid stagger" data-lightbox-gallery>@foreach($design['gallery'] as $image)<button type="button" data-lightbox-item data-src="{{ $image['image'] }}" data-alt="{{ $image['alt'] }}" data-caption="{{ $image['caption'] }}"><img src="{{ $image['image'] }}" alt="{{ $image['alt'] }}" loading="lazy"><span>ขยายภาพ</span></button>@endforeach</div></div></section>@endif
@include('site.partials.contact')
<div class="lightbox" data-lightbox hidden role="dialog" aria-modal="true" aria-label="แกลเลอรีภาพ"><button data-lightbox-close aria-label="ปิด">×</button><button data-lightbox-prev aria-label="ภาพก่อนหน้า">‹</button><figure><img data-lightbox-image alt=""><figcaption data-lightbox-caption></figcaption></figure><button data-lightbox-next aria-label="ภาพถัดไป">›</button></div>
@endsection
